"""New Migration

Revision ID: b632deb31672
Revises: edf9b343aaff
Create Date: 2021-10-04 17:01:16.402237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b632deb31672'
down_revision = 'edf9b343aaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
