"""New Migration

Revision ID: edf9b343aaff
Revises: 608e42f1a574
Create Date: 2021-10-04 15:55:00.596977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf9b343aaff'
down_revision = '608e42f1a574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
